
project_id = "ysykvckvggaqykhhntyo"

[functions.oauth-callback-linkedin]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.naka-user-migrate]
verify_jwt = false

[functions.naka-kb-import]
verify_jwt = false

[functions.naka-prompt-set-root]
verify_jwt = false

[functions.naka-kb-upsert-tenant-doc]
verify_jwt = false

[functions.naka-prompt-set-tenant]
verify_jwt = false

[functions.naka-history-migrate]
verify_jwt = false

[functions.aa-assets-upload]
verify_jwt = false

[functions.aa-assets-register]
verify_jwt = false

[functions.aa-assets-policy]
verify_jwt = false

[functions.aa-payments-quote]
verify_jwt = false

[functions.aa-payments-events]
verify_jwt = false

[functions.aa-entitlements-get]
verify_jwt = false

[functions.aa-assets-list]
verify_jwt = false

[functions.aa-assets-get]
verify_jwt = false

[functions.aa-entitlements-list]
verify_jwt = false

[functions.aa-auth-login]
verify_jwt = false

[functions.aa-auth-did]
verify_jwt = false

[functions.aa-assets-share]
verify_jwt = false

[functions.aa-assets-shared]
verify_jwt = false

[functions.aa-assets-revoke]
verify_jwt = false
