
project_id = "odzaacarlkmxqrpmggwe"

[functions."learn-ai"]
verify_jwt = true

[functions."mondai-ai"]
verify_jwt = false
cors = ["*"]
headers = { 
  "Access-Control-Allow-Origin" = "*", 
  "Access-Control-Allow-Headers" = "authorization, x-client-info, apikey, content-type, x-auth-token, x-kb-token, origin",
  "Access-Control-Allow-Methods" = "GET, POST, PUT, DELETE, OPTIONS"
}

[functions."gdrive-proxy"]
verify_jwt = false
cors = ["*"]
headers = { 
  "Access-Control-Allow-Origin" = "*", 
  "Access-Control-Allow-Headers" = "authorization, x-client-info, apikey, content-type, origin", 
  "Access-Control-Allow-Methods" = "POST, OPTIONS"
}
